package com.webstart.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String UserId) {
		set("UserId", UserId);
	}

	public java.lang.String getUserId() {
		return getStr("UserId");
	}

	public void setUserName(java.lang.String UserName) {
		set("UserName", UserName);
	}

	public java.lang.String getUserName() {
		return getStr("UserName");
	}

	public void setPassword(java.lang.String Password) {
		set("Password", Password);
	}

	public java.lang.String getPassword() {
		return getStr("Password");
	}

	public void setSecretkey(java.lang.String Secretkey) {
		set("Secretkey", Secretkey);
	}

	public java.lang.String getSecretkey() {
		return getStr("Secretkey");
	}

	public void setOnline(java.lang.String Online) {
		set("Online", Online);
	}

	public java.lang.String getOnline() {
		return getStr("Online");
	}

	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}

	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	public void setEnabled(java.lang.String Enabled) {
		set("Enabled", Enabled);
	}

	public java.lang.String getEnabled() {
		return getStr("Enabled");
	}

	public void setDeleteMark(java.lang.String DeleteMark) {
		set("DeleteMark", DeleteMark);
	}

	public java.lang.String getDeleteMark() {
		return getStr("DeleteMark");
	}

}
