package com.webstart.models;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("Base_Permission", "[permissionid]", Permission.class);
		arp.addMapping("Base_Role", "[roleid]", Role.class);
		arp.addMapping("Base_RoleUserRelation", "[roleuserrelationid]", RoleUserRelation.class);
		arp.addMapping("Base_User", "[userid]", User.class);
	}
}

