package com.webstart.models;

import com.webstart.models.base.BaseRoleUserRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleUserRelation extends BaseRoleUserRelation<RoleUserRelation> {
	public static final RoleUserRelation dao = new RoleUserRelation().dao();
}
