package com.webstart.models;

import com.jfinal.plugin.activerecord.Db;
import com.webstart.models.base.BaseUser;

import java.util.Collection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public Collection<Permission> getPermissionList(){
		Collection<Permission> permissions=Permission.dao.find("SELECT distinct  bp.* FROM Base_Permission bp WHERE bp.RoleId in(SELECT bru.RoleId FROM Base_User bu,Base_RoleUserRelation bru WHERE bru.UserId=bu.UserId AND bu.UserId=?)",this.getUserId());
		return permissions;
	}

	public Collection<Role> getRoleList() {
		Collection<Role> roles=Role.dao.find("SELECT br.* FROM Base_RoleUserRelation bru,Base_Role br WHERE bru.RoleId=br.RoleId AND bru.UserId=? ",this.getUserId());
		return roles;
	}

	public Collection<String> getRoleNameList() {
		Collection<String> names= Db.query("SELECT br.RoleName FROM Base_RoleUserRelation bru,Base_Role br WHERE bru.RoleId=br.RoleId AND bru.UserId=? ",this.getUserId());
		return names;
	}

}
